modules:
  icmp:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
  icmp_64kb:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      payload_size: 64000