# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: "aspServer"
    static_configs:
      - targets: ["aspServer:9273"]

  - job_name: "dbServer"
    static_configs:
      - targets: ["dbServer:9273"]

  - job_name: "ping-metrics"
    static_configs:
      - targets: ["ping-metrics:8080"]

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://urltomonitor1
          - https://urltomonitor2
          - https://urltomonitor3
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox_exporter:9115

  # - job_name: 'blackbox-ping'
  #   metrics_path: /probe
  #   params:
  #     module: [icmp]
  #   static_configs:
  #   - targets:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #     - 1.1.1.1
  #     - 1.0.0.1
  #     - 208.67.222.222
  #     - 208.67.220.220
  #     - 9.9.9.9
  #     - 149.112.112.112
  #     - 198.41.0.4
  #     - 192.203.230.10  # <== Put here your targets
  #   relabel_configs:    # <== This comes from the blackbox exporter README
  #   - source_labels: [__address__]
  #     target_label: __param_target
  #   - source_labels: [__param_target]
  #     target_label: instance
  #   - target_label: __address__
  #     replacement: blackbox_exporter_ping:9116 # Blackbox exporter.

  - job_name: 'blackbox-ping'                                                                                                                                                                      
    metrics_path: /probe                                                                                                                                                                      
    params:                                                                                                                                                                                   
      module: [icmp]
    scrape_interval: 5s
    scrape_timeout: 2s      #ping                                                                                                                                                                    
    static_configs:                                                                                                                                                                           
      - targets: ['8.8.8.8', '8.8.4.4']                                                                                                                                                            
        labels:                                                                                                                                                                               
          group: 'Build'                                                                                                                                                                   
      - targets: ['1.1.1.1', '1.0.0.1', '208.67.222.222']                                           
        labels:                                                                                                                                                                               
          group: 'RND' 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter_ping:9115



