# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

  - job_name: "aspServer"
    static_configs:
      - targets: ["aspServer:9273"]

  - job_name: "dbServer"
    static_configs:
      - targets: ["dbServer:9273"]

  - job_name: 'oracle-db-exporter'
    static_configs:
      - targets: ['192.168.8.189:9161']

  # Example job for node_exporter
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://fabmobile.firstatlanticbank.com.gh
        - https://fabinternet.firstatlanticbank.com.gh
        - https://ibank.firstatlanticbank.com.gh:5000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
  # - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
  #   static_configs:
  #     - targets: ['blackbox-exporter:9115']

  - job_name: 'blackbox-ping'                                                                                                                                                                      
    metrics_path: /probe                                                                                                                                                                      
    params:                                                                                                                                                                                   
      module: [icmp]
    scrape_interval: 5s
    scrape_timeout: 2s      #ping                                                                                                                                                                    
    static_configs:                                                                                                                                                                           
      - targets: ['8.8.8.8', '8.8.4.4', '1.1.1.1', '1.0.0.1', '208.67.220.220']                                                                                                                                                            
        labels:                                                                                                                                                                               
          group: 'ATMs'                                                                                                                                                                   
      - targets: ['1.1.1.1', '192.168.8.104', '208.67.222.222','149.112.112.112','192.203.230.10','192.168.8.187', '192.168.8.188']                                           
        labels:                                                                                                                                                                               
          group: 'Host Servers' 
      - targets: ['4.4.4.4','7.7.7.7']
        labels:
          group: 'VPNs'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter-ping:9115

  - job_name: 'blackbox-ping-64kb'                                                                                                                                                                      
    metrics_path: /probe                                                                                                                                                                      
    params:                                                                                                                                                                                   
      module: [icmp_64kb]
    scrape_interval: 30s
    scrape_timeout: 2s      #ping                                                                                                                                                                    
    static_configs:                                                                                                                                                                           
      - targets: ['8.8.8.8', '8.8.4.4', '1.1.1.1', '1.0.0.1', '208.67.220.220']                                                                                                                                                            
        labels:                                                                                                                                                                               
          group: 'ATMs Network'                                                                                                                                                                   
      - targets: ['1.1.1.1', '192.168.8.104', '208.67.222.222','149.112.112.112','192.203.230.10','192.168.8.188', '192.168.8.187']                                           
        labels:                                                                                                                                                                               
          group: 'Host Servers Network' 
      - targets: ['4.4.4.4','7.7.7.7']
        labels:
          group: 'VPNs'
  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter-ping:9115
  - job_name: 'virtual-hosts'
    scrape_interval: 6s
    scrape_timeout: 5s
    static_configs:
            - targets: ['192.168.8.187:9182', '192.168.8.188:9182']
  - job_name: 'wildfly'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.8.187:9990']
          


